apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipvlan-deploy
spec:
  selector:
    matchLabels:
      app: ipvlan-alpine
  replicas: 2
  template:
    metadata:
      labels:
        app: ipvlan-alpine
      annotations:
        k8s.v1.cni.cncf.io/networks: ipvlan-1001
    spec:
      volumes:
      - name: tftpboot	  # The name of the volume
        configMap:
          name: py-tftpboot
      containers:
        - name: ipvlan-alpine
          image: pinrojas/net-test:0.31
          imagePullPolicy: Never
          command: ["sleep"]
          args: ["10000000"]
          env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
