apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipvlan-1001-deploy
spec:
  selector:
    matchLabels:
      app: ipvlan-1001-alpine
  replicas: 2
  template:
    metadata:
      labels:
        app: ipvlan-1001-alpine
      annotations:
        k8s.v1.cni.cncf.io/networks: ipvlan-1001
    spec:
      containers:
        - name: ipvlan-1001-alpine
          image: pinrojas/cassowary:0.33
          imagePullPolicy: Never
          command: ["sleep"]
          args: ["10000000"]
          env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipvlan-1002-deploy
spec:
  selector:
    matchLabels:
      app: ipvlan-1002-alpine
  replicas: 2
  template:
    metadata:
      labels:
        app: ipvlan-1002-alpine
      annotations:
        k8s.v1.cni.cncf.io/networks: ipvlan-1002
    spec:
      containers:
        - name: ipvlan-1002-alpine
          image: pinrojas/cassowary:0.33
          imagePullPolicy: Never
          command: ["sleep"]
          args: ["10000000"]
          env:
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
