---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-1003
spec:
  config: '{
  "cniVersion": "0.4.0",
  "name": "ipvlan-1003",
  "plugins": [{
    "type": "ipvlan",
    "master": "VLAN-1003",
    "ipam": {
      "type": "host-local",
      "ranges": [
          [ 
            { 
              "subnet": "10.1.103.0/24",
					    "rangeStart": "10.1.103.20",
					    "rangeEnd": "10.1.103.50",
					    "gateway": "10.1.103.1"              
            }
          ]
        ],
        "routes": [
          {
            "dst": "10.6.103.0/24",
            "gw": "10.1.103.1"
          },
          {
            "dst": "10.254.254.240/28",
            "gw": "10.1.103.1"
          }
        ]
     }
  }]
}'
