apiVersion: apps/v1
kind: Deployment
metadata:
  name: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pushgw-app
  template:
    metadata:
      labels:
        app: pushgw-app
    spec:
      containers:
        - name: pushgateway
          image: prom/pushgateway:latest
          imagePullPolicy: Never  
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /#/status
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /#/status
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
spec:
  type: NodePort
  selector:
    app: pushgw-app
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 9091
      targetPort: 9091
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
